service: serverless-guru-crud-app # name of the service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage ,'dev'} 
  environment:
    USER_TABLE: {"Ref": UserTable} # this will get the User table name from the resources/tables/UserTable.yml

package:
  individually: true # package individual lambda 
  patterns:
    - '!screenshots/**'
    - '!layers/**'
    - '!node_modules/**'
    - '!package.json'

# provide individual permission for lambda 
plugins:
  - serverless-iam-roles-per-function

layers:
  nodejs:
    package:
      artifact: layers/nodejs.zip
    name: ${opt:stage}-nodejs
    compatibleRuntimes:
      - nodejs16.x
    compatibleArchitectures:
      - x86_64
      - arm64

functions: # all the lambda functions are defined here
  - ${file(./resources/lambda.yml)}

resources:
  - ${file(./resources/dynamodb.yml):resources}