resources:
  Resources:
    # the User table contains the details of the Users like, name,email,id, isDeleted etc..
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users-Table-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: isDeleted
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailGSI
            KeySchema:
              - AttributeName: email #this index is created to fetch a single user based on the email and isDeleted attribute
                KeyType: HASH
              - AttributeName: isDeleted
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: isDeletedGSI #this index is created to fetch all users based on isDeleted attribute
            KeySchema:
              - AttributeName: isDeleted
                KeyType: HASH
            Projection:
              ProjectionType: ALL
